### ISSUE TITLE
IList.value breaks encapsulation

### ISSUE THREAD

**Issue by f3ath** [fpdart/immutables#10]
`IList.value` allows state change:

```dart
foo = IList([1, 2, 3]);
foo.values.add(4); // oops
```

**Comment by shindakioku** [comment]
a) Return new List for value getter
b) Remove this getter

**Comment by shindakioku** [comment]
https://github.com/fpdart/immutables/commit/930da7fbe39a75e8460bc0b9586c49d2b71115a6

Thanks!
